name: CI Build

on:
  push:
    branches: [ main, develop ]
  pull_request:
    branches: [ main ]

jobs:
  build-and-test:
    runs-on: ubuntu-latest
    
    name: Build, Test and Security Check
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
      
    - name: Set up JDK 21
      uses: actions/setup-java@v4
      with:
        java-version: '21'
        distribution: 'temurin'
        
    - name: Cache Maven dependencies
      uses: actions/cache@v4
      with:
        path: ~/.m2
        key: ${{ runner.os }}-m2-${{ hashFiles('**/pom.xml') }}
        restore-keys: ${{ runner.os }}-m2
        
    - name: Run tests
      run: mvn clean test
      
    - name: Generate test report
      uses: dorny/test-reporter@v1
      if: success() || failure()
      with:
        name: Maven Tests (Java 21)
        path: target/surefire-reports/*.xml
        reporter: java-junit
        
    - name: Upload coverage reports to Codecov
      uses: codecov/codecov-action@v4
      with:
        file: target/site/jacoco/jacoco.xml
        fail_ci_if_error: false
        
    - name: Build with Maven
      run: mvn clean package -DskipTests
      
    - name: Upload build artifacts
      uses: actions/upload-artifact@v4
      with:
        name: jar-artifacts
        path: target/*.jar
        
    - name: Test CLI functionality
      run: |
        java -jar target/NarrativeGenerator-1.0-SNAPSHOT.jar --help
        java -jar target/NarrativeGenerator-1.0-SNAPSHOT.jar --mode=BUNDLE_WITH_NARRATIVES src/test/resources/BundleExampleIntensivstation.json > /dev/null

  security:
    runs-on: ubuntu-latest
    continue-on-error: true  # Don't fail the entire workflow if security check fails
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
      
    - name: Set up JDK 21
      uses: actions/setup-java@v4
      with:
        java-version: '21'
        distribution: 'temurin'
        
    - name: Cache Maven dependencies
      uses: actions/cache@v4
      with:
        path: ~/.m2
        key: ${{ runner.os }}-m2-${{ hashFiles('**/pom.xml') }}
        restore-keys: ${{ runner.os }}-m2
        
    - name: Cache OWASP NVD Database
      uses: actions/cache@v4
      with:
        path: ~/.m2/repository/org/owasp/dependency-check-data
        key: ${{ runner.os }}-nvd-${{ github.run_number }}
        restore-keys: |
          ${{ runner.os }}-nvd-
        
    - name: Run OWASP Dependency Check
      run: |
        # Run dependency check with better error handling
        mvn org.owasp:dependency-check-maven:check \
          -Dformat=HTML,JSON \
          -DfailBuildOnCVSS=8 \
          -DskipProvidedScope=true \
          -DskipTestScope=true || echo "Security scan completed with warnings"
      continue-on-error: true
      
    - name: Upload security reports
      uses: actions/upload-artifact@v4
      if: always()
      with:
        name: security-reports
        path: |
          target/dependency-check-report.html
          target/dependency-check-report.json